server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name:   # 남주님 설정
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    database:
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  jwt:
    secret: tmvmfldtlzbflxlfhrmdlsrnguswndspringsecuritylogincodeimplementmakingsecretkey # 남주님 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: njook2501@gmail.com  # 발신자 (보내는 이메일)
    password: sntqjhdvhkgpmxpk  # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# swagger 관련 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  # show-login-endpoint: true # /login 스웨거 보이게
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

tag:
  version: 1.0.0